data_path: "Data/processed/cleaned_master_df.csv"
label_type: "binary" #binary, multiclass
use_grid_search: False

feature_cols:
  - age_band
  - highest_education
  - imd_band
  - num_of_prev_attempts
  - studied_credits
  - total_n_days
  - avg_total_sum_clicks
  - n_days_oucontent
  - avg_sum_clicks_quiz
  - avg_sum_clicks_forumng
  - avg_sum_clicks_homepage

model_name: "random_forest"  # logistic_regression, random_forest, knn, svm, sgd, mlp

all_model_params:
  logistic_regression:
    lr: 0.1 
    epochs: 100 
  random_forest:
    n_estimators: 100
    max_depth: 10 
    min_samples_split: 2 
    max_features: null 
    random_state: 42 
  knn:
    k: 2    
  svm: 
    lr: 0.001
    epochs: 100 
    C: 1.0
  sgd:
    lr: 0.01
    epochs: 100 
  mlp: 
    hidden_sizes: [100] 
    output_size: 1
    lr: 0.1
    epochs: 100
  perceptron:
    epochs: 100
    lr: 1.0 
  decision_tree:
    max_depth: 5
    min_samples_split: 2

val_size: 0.1
test_size: 0.2
scale: true
random_state: 42